### ISSUE TITLE
saveMetadata() 

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#11]
This function currently saves the input information for the experiment under a folder 'filename', all other files in the experiment will also need access to this although will function using their own filename. 

I have done a dirty fix running the function twice in the first cell to also have it under the HT_filename for example although this issue will persist with the DLC data for instance, where the groups and experimental info will be the same. 

In short: one experimental metadata many experimental files using filename to store under is not suitable 

merged with https://github.com/jjb-hub/phd/issues/24

For each experiment, there is a unique (relatively - there is overlap although this is something input by use with new experiment) list of both REGIONS and COMPOUNDS both with subclassifications (see attached). Currently, there is a COLUMN_ORDER={} in constants however it is not a true constant. There are also subclassifications in the correct order for both - this should all be condensed.

Also, the subclassifications could be used to answer prompts.

![image](https://github.com/jjb-hub/phd/assets/59827951/50907318-197f-45e0-950b-875c11c5fc7a)

**Comment by remicorne** [comment]
@jjb-hub The flow will be changed in the following way: no more save metadata! Each 'filename' folder will have the different mappings (treatment, regionsubclass...) and they will be edited manually directly in the json file, its pointless to edit in the notebook and apply save metadat, just an extra step for nothing

**Comment by jjb-hub** [comment]
@remicorne manually opening and changing a json doesn't sound pdd friendly before you make the change please be clear on how I can do it

**Comment by jjb-hub** [comment]
this is now redundant because we have the input info stored in the dictionaries that will be out in a folder @remicorne will make that will then be copied into the new folder with the new excel DOI_data_HPLC for example
