### ISSUE TITLE
unable to see outlier indicated for removal 

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#15]
![Screen Shot 2023-09-28 at 13 23 57](https://github.com/jjb-hub/phd/assets/120100465/8d9d75c7-8be3-4377-ab05-0ef883470c7f)
this has happened a few times where I can not see which point is meant to be the outlier maybe the marker could be made bigger? but here I think it just isn't working for some reason: 3MT/DA in VM
![Screen Shot 2023-09-28 at 13 25 19](https://github.com/jjb-hub/phd/assets/120100465/e59cf510-d66c-42e1-959a-43df487abb6e)

**Comment by jjb-hub** [comment]
happened again for the 3rd but not 1,2 or 4th outlier for 5HIAA/5HT in SC

**Comment by remicorne** [comment]
Some values are Nan, most likely only for ratios (zerodivision), do we remove them by default?

This would happen when the compoundAndRatiosDf is originallly calculated

**Comment by jjb-hub** [comment]
happened again with 5HIAA/5HT in SC dose response 4 outliers were prompted for but i could not see what no 3 was!
![image](https://github.com/jjb-hub/phd/assets/120100465/a6640b25-1e56-4bab-ba5c-f04d9ceb9e6a)

**Comment by jjb-hub** [comment]
#25 @remicorne
