### ISSUE TITLE
histogram CANT SELECT REGION WITH LOWERCASE KEY e.g. 'vH' 

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#17]
![Screen Shot 2023-09-28 at 16 04 33](https://github.com/jjb-hub/phd/assets/120100465/b3254065-f05c-47f0-b644-c5f4487d00f2)
this was for 5HT *which i need for my presentation next week

**Comment by jjb-hub** [comment]
the first time it asks to choose from the list everything is caps sensitive (which it should be!) then after goes to all caps no matter what i put vH VH Vh vh it will not accept

**Comment by remicorne** [comment]
@jjb-hub Is it fine with you if we just put everything in caps from the start or would you like to maintain the names as they are?

**Comment by jjb-hub** [comment]
all case sensitive now i believe - remi is that correct?
