### ISSUE TITLE
PDD ideas for searchers()

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#19]
which compound do we see an increase in correlations relative to vehicles?
which correlogram is most different between groups?

**Comment by remicorne** [comment]
@jjb-hub  Both are possible to do.
@pdeuwaer  
1 & 2 - We will need to reduce to field of search, don't forget that possible number of correlograms is:
(10 compounds * 10 compounds) * (10 compounds * 10 compounds) = 1000 compound correlograms (square included)
(30 regions * 30 regions ) * (30 regions  * 30 regions ) = 27000 regions correlograms (square included)
= 28000 total
2 - We would need some kind of logic/equation that gives a score of difference between two correlograms

**Comment by jjb-hub** [comment]
this will be addressed later when we have functional new data structure and can perform searched in correlograms and graphs and histograms based on stats df for each
