### ISSUE TITLE
handel NaN in correlogram data

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#21]
masking for triangle correlograms does not work with rations 
![Screen Shot 2023-10-02 at 13 39 56](https://github.com/jjb-hub/phd/assets/120100465/dd934c83-5b60-41d6-9567-5082a3a6c2cd)

**Comment by jjb-hub** [comment]
THIS IS NOT A MASK issue - rather it is an issue of how handling of the data is being done!

problemo 1 - when inputting the csv 0 should be taken as NaN this is in the code line 128 getters.py but is not working
![Screen Shot 2023-10-05 at 19 07 21](https://github.com/jjb-hub/phd/assets/120100465/5f5dc918-2f10-40ff-a605-6cd151c5046b)

problemo 2 - the correlogram function should have this n_minimum = 5 i believe but it is still keeping all 0 values (yes probably cause 0 is not NaN) and furthermore it is still plotting the region in this case (SJ,dH...) even when the correlogram)df is just a column/row of NaN this is not good as it seems the region does not correlate wheninfact it HAS NO DATA!
![Screen Shot 2023-10-05 at 19 07 52](https://github.com/jjb-hub/phd/assets/120100465/0b6daed7-86c2-4ea4-83f6-3d1afb74d451)

**Comment by remicorne** [comment]
@jjb-hub please work on sentence syntax, i know you're dyslexic so i'll forgive the fused words but you're not dysyntactic i've heard you speak english

**Comment by remicorne** [comment]
@jjb-hub the code you provide does the opposit: replaces nan with 0

**Comment by jjb-hub** [comment]
this is the point of the n=5 for a minimum if there are >5 n to correlate then the whole group is dropped and the import should be NaN! 0 is manufacturing data!!!! SHIT i am sorry i didn't catch it earlier

**Comment by remicorne** [comment]
@jjb-hub Im trying to find a solution for nan correlations but nothing nice so far
![image](https://github.com/jjb-hub/phd/assets/59827951/55075a45-d011-4a1d-b8b6-9b0b8ee29491)
