### ISSUE TITLE
stats quantitativeSummary() 

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#22]
for new data sets it may be nice to have a simple quantitative summary unlike the one existing now but more like this
![Screen Shot 2023-10-02 at 19 18 39](https://github.com/jjb-hub/phd/assets/120100465/27846996-6c68-4753-9b10-d8052f7b45cb)

**Comment by remicorne** [comment]
@jjb-hub Good idea but you'll need to sketch me out the code that creates this figure

**Comment by jjb-hub** [comment]
@remicorne I wrote the code to create it (hence i am assigned) you may see it is called quantativeSummary() it is a good example of me trying to apply your 'modular' functions your comments and integration would be very helpful

 - it is missing your stats which I would pull from the aggstats or the df that will have all stats with current outlier selection and then plot it but for that I would need again - stat annotator
 - it also raises issues with the modularity of the histogram function you have - not sure we need two but i had to make another for this plot...

**Comment by jjb-hub** [comment]
#ISSUES with 

stats is not done in a reversable way (only for a single compound and several regions)

star plotting too high above bars (outliers may be being used to set y_coord ?) check outlier handling 

different quantities e.g. DA high in striatum need to be dealt with (brokenaxis)

**Comment by jjb-hub** [comment]
done by looping ax.patches

possible soloution also for smaller hist of we want to get ride of stat annotator @remicorne 

function needs:
- to be made reversabe ie for all coumounds in one region 
- to integrate break axis for DA for instance 
- stats is currently rerunning all every plot (not efficient)
