### ISSUE TITLE
integrate subclassifications and COLUMN_ORDER in constants 

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#24]
For each experiment, there is a unique (relatively - there is overlap although this is something input by use with new experiment) list of both REGIONS and COMPOUNDS both with subclassifications (see attached). Currently, there is a COLUMN_ORDER={} in constants however it is not a true constant. There are also subclassifications in the correct order for both - this should all be condensed. 

Also, the subclassifications could be used to answer prompts. 
![Screen Shot 2023-10-05 at 18 16 33](https://github.com/jjb-hub/phd/assets/120100465/bd8732ad-db70-469e-bf8a-e09da4d51667)

**Comment by remicorne** [comment]
We're going to start using json files to store this shit, ill remove the save metadata function as well

**Comment by remicorne** [comment]
Merged with https://github.com/jjb-hub/phd/issues/11
