### ISSUE TITLE
fix prompting

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#25]
1.  find a way to subselect without having to rewrite the list as can not be copied in notebook
                      a. maybe remove compounds from the list offered?
                      b. subselection of compounds/regions see region_subclassification / compound_subclassification

3. Check if data exists before offering for region/compound

**Comment by remicorne** [comment]
@jjb-hub Is it acceptable to just print the list? its possible to copy paste from whats printed in the cell

I don't get your point in b

**Comment by jjb-hub** [comment]
#15

**Comment by jjb-hub** [comment]
issue still exists will be refactored with current broken prompting
