### ISSUE TITLE
quantitativeSummary() for Tunisia 

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#28]
Ideally, the case here would be I set the quantitativeSummay() to run and for the plot it is doing it generates all of the highest level stats it needs, given the experiment,  compound and regions selected i.e. one-way for dose_response and two-way for agonist_antagonsits and plot the stars above each set of hues

MINIMUM NEED: stat annotator plotting highest level stats (in this case for the conference I just need one-way ANOVA for the dose-response 5HIAA/5HT with a star over each region passing)

JJB todo: add axspan with labels for subregion classification and add brokenaxis (DA especialy)

**Comment by jjb-hub** [comment]
![Screen Shot 2023-10-09 at 15 55 04](https://github.com/jjb-hub/phd/assets/120100465/b097f6d1-9197-44c5-9a0b-6af11d614153)
quant_stats has multiple things under 'test' I do not understand how this will work when you have more than one test prior to post hoc (tukey) i.e. two way ANOVA / one way ANOVA which should both be saved for agonist_antagonist experiments

**Comment by jjb-hub** [comment]
to go from quantitative stats df to stars on quantitativeSummary():

*assuming quantitative stats df is filled for hist to plot

Create a mapping between regions and their corresponding p-values for a given compound (or visa versa for a single region with several compounds)

if we want to move away from stat annotator something like this: # Annotate significance stars above regions based on p-values
for p in ax.patches:
    region = p.get_x()
    if region in region_to_pvalue:
        p_value = region_to_pvalue[region]
        if p_value < 0.001:
            stars = '***'
        elif p_value < 0.01:
            stars = '**'
        elif p_value < 0.05:
            stars = '*'
        else:
            stars = ''
        ax.annotate(stars, (p.get_x() + p.get_width() / 2., p.get_height()), ha='center', va='center',
                    size=10, xytext=(0, 10), textcoords='offset points', color='red', weight='bold')

**Comment by remicorne** [comment]
> ![Screen Shot 2023-10-09 at 15 55 04](https://user-images.githubusercontent.com/120100465/273606807-b097f6d1-9197-44c5-9a0b-6af11d614153.png) quant_stats has multiple things under 'test' I do not understand how this will work when you have more than one test prior to post hoc (tukey) i.e. two way ANOVA / one way ANOVA which should both be saved for agonist_antagonist experiments

@jjb-hub Try and see for yourself its should save it as well. 1 experiment = 1 line per test

**Comment by remicorne** [comment]
> to go from quantitative stats df to stars on quantitativeSummary():
> 
> *assuming quantitative stats df is filled for hist to plot
> 
> Create a mapping between regions and their corresponding p-values for a given compound (or visa versa for a single region with several compounds)
> 
> if we want to move away from stat annotator something like this: # Annotate significance stars above regions based on p-values for p in ax.patches: region = p.get_x() if region in region_to_pvalue: p_value = region_to_pvalue[region] if p_value < 0.001: stars = '_**' elif p_value < 0.01: stars = '**' elif p_value < 0.05: stars = '_' else: stars = '' ax.annotate(stars, (p.get_x() + p.get_width() / 2., p.get_height()), ha='center', va='center', size=10, xytext=(0, 10), textcoords='offset points', color='red', weight='bold')

@jjb-hub Ill let you deal with this
