### ISSUE TITLE
justStats() buggy

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#33]
#issues
#duplicating rows not updating them #REAL issue easy fix
#saving tukey  -  p_value cols are a bit odd for this test as its between all groups for experiment - not sure how to improve but improvement need can close issue without

**Comment by remicorne** [comment]
https://github.com/jjb-hub/phd/pull/37

**Comment by jjb-hub** [comment]
ADDITIONALLY: 
In quantitativeSummary(), I use :     
quant_stats_df = subselectDf(getQuantitativeStats(filename), {'experiment':experiment, 'compound':compound, 'region': region, 'test':test })

the issue here is that if I have not run juststats() for the same regions and compound then it has nothing in the df / alternatively if I run just stats within the function it will continue to duplicate the stats in the df
