### ISSUE TITLE
list integration in histogram()

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/phd#35]
I would like to be able to respond to the prompts with lists - 
seeing as a histogram is only ver 1 region and 1 compound (otherwise it would be quantitativeSummary() ) then we could have the input taken as a list also if i would like to generate say DA histograms for ['PL','OF','AC'] right now i feel i have been through the prompts 1000 times

**Comment by remicorne** [comment]
https://github.com/jjb-hub/phd/pull/37
