### ISSUE TITLE
Remi changes

### ISSUE THREAD

**Issue by pdeuwaer** [jjb-hub/phd#9]
- Stats logic
- Standardize caps
- Force yes or no, not just anything else
- Check if data exists before asking for region/compound
- Correlogram list more convient (remove flag to just remove or create new list/change order)
- To many prompts, need code mode as well + list
- Outlier test must be preset for whole experiment
- Compound ratios don't save because of slash in name
- Find more convenient way to store stat info with graph ("passed: one way, two way" (not tukey cuz it always has to pass))
- Loop with all default outlier stuff to be done (all regions, all compounds + specific ratios)

**Comment by jjb-hub** [comment]
![WhatsApp Image 2023-08-14 at 8 23 57 PM](https://github.com/jjb-hub/phd/assets/120100465/6afb0193-d8db-4bb0-8088-d498515f4f4d)

**Comment by jjb-hub** [comment]
I have just pushed to my branch the integration HT histograms: could you integrate the stats logic, outliers, and prompts?

happy to do it together as i may learn faster that way!

**Comment by jjb-hub** [comment]
STATS searcher:  chose a compound or ratio and search for statistical significance (in Twoway or oneway or both )

**Comment by jjb-hub** [comment]
JJB done:
Correlogram list more convenient (remove flag to just remove or create new list/change order) - will now take list if given
